-- supabase/migrations/001_create_rsvp_table.sql
create table if not exists public.rsvp (
  id bigint generated by default as identity primary key,
  name text not null,
  guests integer not null check (guests >= 1 and guests <= 10),
  phone text not null check (phone ~ '^[0-9]{11}$'),
  created_at timestamp with time zone default now()
);

-- 启用行级安全（只允许插入和读取）
alter table public.rsvp enable row level security;

-- 允许任何人插入RSVP（客人登记）
create policy "Allow public insert" on public.rsvp
  for insert with check (true);

-- 允许任何人读取RSVP（用于统计人数）
create policy "Allow public select" on public.rsvp
  for select using (true);

-- 启用Realtime订阅
alter publication supabase_realtime add table public.rsvp;
